In [3]:
import numpy as np
import time

In [4]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [i**2 for i in py_list]
end = time.time()

print(end-start)

np_arr = np.array(py_list)
start = time.time()
sq_arry = np_arr**2 
end = time.time()
print(end-start)


1.8448498249053955
0.054663896560668945


In [12]:
#memory
import sys

print(sys.getsizeof(py_list)*len(py_list))

print(np_arr.nbytes)

8000056000000
8000000


In [15]:
#Create - from lists
arr = np.array([1,2,4,5,6])
print(arr.dtype,arr.shape)

arr2 = np.array([1,2,4,5,6,"prime"])
print(arr2.dtype, arr2.shape)

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d.dtype,arr2d.shape)

int64 (5,)
<U21 (6,)
int64 (3, 3)


In [23]:
#Create
arr1 = np.zeros((2,3), dtype="int64")
print(arr1,arr1.shape)

arr2 = np.ones((2,3))
print(arr2,arr2.shape)

arr3 = np.full((3,4), 100)
print(arr3,arr3.shape)

arr4 = np.eye(2)
print(arr4,arr4.shape)

arr5 = np.arange(1,11,2)
print(arr5,arr5.shape)

arr6 = np.linspace(1,100,4)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0.]
 [0. 1.]] (2, 2)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [ ]:
#Properties